name: Coverage

on: pull_request

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Jest test with coverage
        uses: ArtiomTr/jest-coverage-report-action@v2.0.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}